### ISSUE TITLE
UCHILE_ROBOT ¿Para qué sirve seleccionar "all"?

### ISSUE THREAD

**Issue by ristofer** [uchile-robotics/uch_system#2]
había seteado UCHILE_ROBOT para "all" pero de esa manera no se puede usar el robot_factory.  Cambié a "bender" pero creo que se debe compilar todo de nuevo para que funcione.

**Comment by mpavezb** [comment]
Exacto.

*robot_factory* ni *robot-console* están adecuadas para uso multirobot. Es algo que debo solucionar.

La recompilación es necesaria, pues evita mezclar dependencias de distintos robots en un mismo workspace. La variable `UCHILE_ROBOT` permite elegir entre distintos overlays de ROS, los que tienen espacios build y devel distintos. Debo explicar eso en la documentación.

**Comment by mpavezb** [comment]
La robot console ahora soporta multirobots!
