### ISSUE TITLE
aiml

### ISSUE THREAD

**Issue by nmarticorena** [uchile-robotics/uch_system#6]
el instalador no agrega aiml, eso si el repo que se usaba no es necesario si no que solamente basta un 
`sudo apt-get install python-aiml`

**Comment by mpavezb** [comment]
Hay que ver si basta con agregar `aiml` al archivo `package.xml` respectivo e intentar correr el comando clásico: `rosdep install ..`

**Comment by nmarticorena** [comment]
Vale lo revisare despues, eso si tengo una duda como se llamaba el repo que usabamos, creo que con solo importar aiml hay cosas que no funcionan

Enviado desde mi iPhone
