### ISSUE TITLE
Rosaria

### ISSUE THREAD

**Issue by rdelgadov** [uchile-robotics/uch_system#9]
Al compilar los forks con `cdb forks && cd .. && catkin_make` falla por:

![image](https://user-images.githubusercontent.com/11382169/55158169-00377480-513d-11e9-92fb-302c7af66169.png)

**Comment by rdelgadov** [comment]
Se soluciona con `rosdep install rosaria`

**Comment by mpavezb** [comment]
Hola, para instalar los forks basta seguir el documento de instalación, específicamente:

```bash
# instalar dependencias
cdb forks && rosdep install --from-paths . --ignore-src --rosdistro=indigo -y

# Compilar
cdb forks && cd .. && catkin_make
```

Posiblemente modificando `indigo` por la distro actual.
De lo contrario, hay que actualizar el documento :)
